config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :trips, only: [:new, :create, :show, :update, :index, :edit, :destroy] do
    resources :flats, only: [:index, :show]
    resources :restaurants, only: [:index, :show]
    resources :activities, only: [:index, :show]
  end

  resources :flats, only: [] do
    resources :flats_bookings, only: [:create]
  end
  resources :flats_bookings, only: [] do
    resources :flat_reviews, only: [:create]
  end

  resources :restaurants, only: [] do
    resources :restaurants_bookings, only: [:create]
  end
  resources :restaurants_bookings, only: [] do
    resources :restaurant_reviews, only: [:create]
  end

  resources :activities, only: [] do
    resources :activities_bookings, only: [:create]
  end
  resources :activities_bookings, only: [] do
    resources :activity_reviews, only: [:create]
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :trips, through: :booking_flats
  has_many :booking_flats
  has_many_attached :photos
  
  has_many :booking_flats, dependent: :destroy
  has_many :flat_reviews,  through: :booking_flats

  validates :name, presence: true
  validates :address, presence: true
  validates :price, presence: true
  validates :capacity, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def average_rating
    return 5 if flat_reviews.empty?
    sum = 0
    flat_reviews.each do |flat_review|
      sum += flat_review.rating
    end
    @average_rating = sum / flat_reviews.count
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
	before_action :set_flat, only: [:show]
	skip_after_action :verify_policy_scoped, only: :index

	def index
		@trip = Trip.find(params[:trip_id])
		@flats = Flat.near(@trip.location, 20)

		if params[:search]&.fetch(:price_min).present?
			@price_min = params[:search]&.fetch(:price_min)
			@flats = @flats.where("price >= ?", @price_min)
		end

		if params[:search]&.fetch(:price_max).present?
			@price_max = params[:search]&.fetch(:price_max)
			@flats = @flats.where("price <= ?", @price_max)
		end

		@markers = @flats.map do |flat|
			{
				lat: flat.latitude,
				lng: flat.longitude,
				infoWindow: render_to_string(partial: "info_window", locals: { flat: flat }),
				info_price: "#{flat.price.round}€"				
			}
		end
	end

	def show
		@booking_flat = BookingFlat.new
		@flat = Flat.find(params[:id])
		@trip = Trip.find(params[:trip_id])
		@markers = [{ lat: @flat.latitude, lng: @flat.longitude, infoWindow: render_to_string(partial: "info_window", locals: { flat: @flat }),
		info_price: @flat.price }]
		@duration = @trip.end_date - @trip.start_date
		@price = @flat.price * @duration
		authorize(@flat)
		@flatreservation = BookingFlat.find_by(flat: @flat, trip: @trip)
		@flat_review = FlatReview.new
		@flat_reviews = @flat.flat_reviews
		@average_rating = @flat_reviews.average(:rating)
	end

	private 

	def set_flat
		@flat = Flat.find(params[:id])
		authorize_flat
	end 

	def authorize_flat
		authorize(@flat)
	end


end

app/views/flats/_info_window.html.erb
<div class="card-window">
  <div class="photo-info">
    <% if flat.photos.any? %>
      <%= cl_image_tag flat.photos.first.key %>
    <% end %>
  </div>
  <h2><%= flat.name %></h2>
  <p><%= flat.address %></p>
</div>

app/views/flats/index.html.erb
<div class="container-fluid py-1">
<%= render 'shared/tab' %>
<div class='margin_filtres'>
  <%= simple_form_for :search, url: trip_flats_path, method: 'GET', html: { class: 'form-inline' } do |f| %>
    <%= f.input :price_min, placeholder: 'prix minimum', label: false, input_html: { value: @price_min} %>
    <%= f.input :price_max, placeholder: 'prix maximum', label: false, input_html: { value: @price_max} %>
    <div>
    <%= f.submit "Rechercher", class: "btn btn-primary hover_btn_search no_border background_color_grey border_light_grey border-right padding-12-px text_color_green" %>
    </div>
  <% end %>
  </div>
  </div>

  <div class="content">
    <div class="cards">
      <% @flats.each do |flat| %>
       <%= link_to trip_flat_path(trip_id: @trip.id, id: flat.id) do %>
          <div class="card-trip">  
            <%= cl_image_tag flat.photos.first.key %>
            <div class="card-trip-infos">
              <div class='card-trip-text'>
                <p><%= flat.address %></p>
                <h2 class="pb-2 mb-2"><%= flat.name %></h2>
              </div>
              <div>
                <p>label : <%= flat.label %></p>
                <h2 class="card-trip-pricing"><%= flat.price %>€</h2>
              </div>
            </div>
          </div> 
       <% end %> 
      <% end %>
    </div>
    <div id="trip-box" style="width: 300px; height: 100vh;">
      <ul class="list-inline nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="t-tab-underlined nav-link active" id="trip-tab" data-toggle="tab" href="#trip" role="tab" aria-controls="trip" aria-selected="false">Mon voyage</a> 
        </li>
        <li class="nav-item">
          <a class="t-tab-underlined nav-link" id="map-tab" data-toggle="tab" href="#map" role="tab" aria-controls="map" aria-selected="true">Carte</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="trip" role="tabpanel" aria-labelledby="trip-tab">
          <div class="trip-column">
            <div class="trip-card-title">
              <h6>Restaurants</h6>
            </div>
            <% unless @trip.restaurants.empty? %>
              <% @trip.restaurants.each do |restaurant| %>
                <div id="trip-card">
                  <div class="left">
                    <p><%= restaurant.name %></p>
                    <p><span><%= restaurant.price %>€/ personne</span></p>
                    <p><%= @trip.start_date %></p>
                  </div>
                  <div class="right">
                    <a data-dismiss="alert" aria-label="Close">
                      <i class="fas fa-times"></i>
                    </a>
                  </div>
                </div>
              <% end %>
            <% end %>
            <div>
              <div class="trip-card-title">
                <h6>Hébergements</h6>
              </div>
              <% unless @trip.flats.empty? %>
                <% @trip.flats.each do |flat| %>
                  <div id="trip-card">
                    <div class="left">
                      <p><%= flat.name %></p>
                      <p><span><%= flat.price %>€/ nuité par personne</span></p>
                      <p><%= @trip.start_date %> - <%= @trip.end_date %></p>
                    </div>
                    <div class="right">
                      <a data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-times"></i>
                      </a>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div>
              <div class="trip-card-title">
                <h6>Activités</h6>
              </div>
              <% unless @trip.activities.empty? %>
                <% @trip.activities.each do |activity| %>
                  <div id="trip-card">
                    <div class="left">
                      <p><%= activity.name %></p>
                      <p><span><%= activity.price %>€/ personne</span></p>
                      <p><%= @trip.start_date %></p>
                    </div>
                    <div class="right">
                      <a data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-times"></i>
                      </a>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="book-box">
              <%= link_to "Réserver", trip_path(@trip), class: "important-btn" %>
            </div>
          </div> <!--end-->
        </div>
        <div class="tab-pane fade"
          id="map"
          role="tabpanel"
          aria-labelledby="map-tab"
          style="width: 300px; height: 100vh;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container-fluid p-4">
  <div class="content">
    <div style='width: 100%'>
      <div>
        <div class='show-title'>
          <%= link_to ('<i class="far return-fa fa-angle-left"></i>').html_safe, trip_flats_path(@trip) %>
          <div>
            <h4><%= @flat.address %></h4>
            <h1><%= @flat.name %></h1>
          </div>
        </div>
        <div class="rounded px-3">
          <div class="gallery">
            <div class="img-principale">
              <%= cl_image_tag @flat.photos.first.key, height: 385, crop: :fill, class:"w-100 h-100" %>
            </div>
            <div class="img-secondaires">
              <% (1..3).each do |number| %>
                <% if @flat.photos[number].nil? %>
                  <button class="img-secondaire btn" type="button" data-toggle="modal" data-target="#exampleModalCenter" style="background-image: url(<%= cl_image_path 'photo.jpg' %>);"></button>
                <% else %>
                  <!-- Button trigger modal -->
                  <button class="img-secondaire btn" type="button" data-toggle="modal" data-target="#exampleModalCenter-<%= number %>" style="background-image: url(<%= cl_image_path @flat.photos[number].key %>);"></button>

                  <!-- Modal -->
                  <div class="modal fade" id="exampleModalCenter-<%= number %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content flat-modal">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <!-- Code carroussel -->
                          <%= cl_image_tag @flat.photos[number].key %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- Flat card -->
      <div class="row p-4">
        <div class="col-md-8">
        
          <p><%= @flat.description %></p>
          <p>Cet hébergement est noté :
            <% @flat.average_rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - @flat.average_rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
          </p>
          <div class="reviews">
          <h2><%= @flat_reviews.count %> commentaires</h2>
            <% @flat_reviews.each do |flat_review| %>
              <p><%= flat_review.user.first_name %></p>
              <p><% flat_review.rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
              <% (5 - flat_review.rating).times do %>
                <i class="far fa-star"></i>
              <% end %>
              </p>
              <p><%= flat_review.content %></p>
            <% end %>
          </div>
          <% if @flatreservation %>
            <div class="review">
              <h3>Laissez une évaluation</h3>
              <%= simple_form_for @flat_review, url: flats_booking_flat_reviews_path(@flatreservation, html: { class: "review_form" }) do |f| %>
                <%= f.input :content, label: false %>
                <%= f.input :rating, collection: (1..5).to_a, label: "notez votre expérience" %>
                <%= f.submit class: "d-none" %>
              <% end %>
            </div>
          <% end %>
          <%#= link_to "Retour aux hébergements", flats_path, class:"btn btn-secondary" %>
        </div>
        <div class="col-md-4">
          <!-- Booking card -->
          <div id="form_booking">
            <div class="d-flex justify-content-between mt-2">
              <div class="important">
                <p><%= @flat.price %>€<span style="font-size: 16px">/ nuité par pers.</span></p>
              </div>
            </div>
            <div>
              <%= simple_form_for [@flat, @booking_flat], url:  flat_flats_bookings_path(@flat) do |f| %>
                <%= f.input :trip_id, as: :hidden, input_html:{value:@trip.id} %>
                <%= f.input :start_date, placeholder: "Date", as: :string, required: false, input_html: { class: "datepicker", value: @trip.start_date}, order: [:day, :month, :year], label: false %>
                <%= f.input :end_date, placeholder: "Date de départ", as: :string, required: false, input_html: { class: "datepicker" }, order: [:day, :month, :year], label: false %>
                <%= f.button :submit, "Réserver", class: "btn btn-primary w-100" %>
              <% end %>
            </div>
            <div class="important">
              <div class="d-flex justify-content-between mt-3">
                <p><strong>Total</strong></p>
                <p><strong><%= @price %>€</strong></p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="p-4">
        <h2>Emplacement</h2>
        <div id="map"
          style="width: 100%; height: 300px; border-radius: 10px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>

    <div id="trip-box" style="width: 300px; height: 100vh;">
      <ul class="list-inline nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="t-tab-underlined nav-link active" id="trip-tab" data-toggle="tab" href="#trip" role="tab" aria-controls="trip" aria-selected="false">Mon voyage</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="trip" role="tabpanel" aria-labelledby="trip-tab">
          <div class="trip-column">
            <div class="trip-card-title">
              <h6>Restaurants</h6>
            </div>
            <% unless @trip.restaurants.empty? %>
              <% @trip.restaurants.each do |restaurant| %>
                <div id="trip-card">
                  <div class="left">
                    <p><%= restaurant.name %></p>
                    <p><span><%= restaurant.price %>€/ personne</span></p>
                    <p><%= @trip.start_date %></p>
                  </div>
                  <div class="right">
                    <a data-dismiss="alert" aria-label="Close">
                      <i class="fas fa-times"></i>
                    </a>
                  </div>
                </div>
              <% end %>
            <% end %>
            <div>
              <div class="trip-card-title">
                <h6>Hébergements</h6>
              </div>
              <% unless @trip.flats.empty? %>
                <% @trip.flats.each do |flat| %>
                  <div id="trip-card">
                    <div class="left">
                      <p><%= flat.name %></p>
                      <p><span><%= flat.price %>€ / nuité par pers.</span></p>
                      <p><%= @trip.start_date %> - <%= @trip.end_date %></p>
                    </div>
                    <div class="right">
                      <a data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-times"></i>
                      </a>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div>
              <div class="trip-card-title">
                <h6>Activités</h6>
              </div>
              <% unless @trip.activities.empty? %>
                <% @trip.activities.each do |activity| %>
                  <div id="trip-card">
                    <div class="left">
                      <p><%= activity.name %></p>
                      <p><span><%= activity.price %>€ / personne</span></p>
                      <p><%= @trip.start_date %></p>
                    </div>
                    <div class="right">
                      <a data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-times"></i>
                      </a>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>