config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :trips, only: [:new, :create, :show, :update, :index, :edit, :destroy] do
    resources :flats, only: [:index, :show]
    resources :restaurants, only: [:index, :show]
    resources :activities, only: [:index, :show]
  end

  resources :flats, only: [] do
    resources :flats_bookings, only: [:create]
  end
  resources :flats_bookings, only: [] do
    resources :flat_reviews, only: [:create]
  end

  resources :restaurants, only: [] do
    resources :restaurants_bookings, only: [:create]
  end
  resources :restaurants_bookings, only: [] do
    resources :restaurant_reviews, only: [:create]
  end

  resources :activities, only: [] do
    resources :activities_bookings, only: [:create]
  end
  resources :activities_bookings, only: [] do
    resources :activity_reviews, only: [:create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Le voyage du futur sera green ! <i class="fas fa-leaf"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar  sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-acanopya.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
       <% if @trip&.persisted? %>
          <!--li class="nav-item active">
            <%= link_to "Mes voyages", trips_path, class: "nav-link" %>
          </li>-->
          <% end %>
        <li class="nav-item dropdown">
          <%= image_tag "wila.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to "Tous mes voyages", trips_path, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_tab.html.erb
<% 
page = local_assigns.fetch(:page,'')
hebergement= page == 'trip-show' ? 'Ajouter un hébergement' : 'Hébergements'
restaurant= page == 'trip-show' ? 'Ajouter un restaurant' : 'Restaurants'
activity= page == 'trip-show' ? 'Ajouter une activité' : 'Activités'

%>
<div class="container pt-4 pb-1">
  <ul class="list-inline tabs-underlined">
    <%# if current_page?(flats_path, restaurants_path, activities_path) %>
      <% if user_signed_in? %>
        <% if @trip&.persisted? %>
          <li>
            <%= link_to hebergement, trip_flats_path(@trip.id, active: :flats), class: "tab-underlined #{ 'active' if params[:active] == 'flats' || params[:active].nil? }", data: {turbolinks: "false"} %>
          </li>
          <li>
            <%= link_to restaurant, trip_restaurants_path(@trip.id, active: :restaurants), class: "tab-underlined #{ 'active' if params[:active] == 'restaurants' }", data: {turbolinks: "false"} %>
          </li>
          <li>
            <%= link_to activity, trip_activities_path(@trip.id, active: :activities), class: "tab-underlined #{ 'active' if params[:active] == 'activities' }", data: {turbolinks: "false"} %>
          </li>
        <% end %>
      <% end %>
    <%# end %>
  </ul>
</div>