config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :trips, only: [:new, :create, :show, :update, :index, :edit, :destroy] do
    resources :flats, only: [:index, :show]
    resources :restaurants, only: [:index, :show]
    resources :activities, only: [:index, :show]
  end

  resources :flats, only: [] do
    resources :flats_bookings, only: [:create]
  end
  resources :flats_bookings, only: [] do
    resources :flat_reviews, only: [:create]
  end

  resources :restaurants, only: [] do
    resources :restaurants_bookings, only: [:create]
  end
  resources :restaurants_bookings, only: [] do
    resources :restaurant_reviews, only: [:create]
  end

  resources :activities, only: [] do
    resources :activities_bookings, only: [:create]
  end
  resources :activities_bookings, only: [] do
    resources :activity_reviews, only: [:create]
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  CATEGORIES = ['Poisson', 'Monde', 'Italienne', 'Japonaise', 'Française']

  has_many :trips, through: :booking_restaurants
  has_many :booking_restaurants
  has_many_attached :photos

  has_many :booking_restaurants, dependent: :destroy
  has_many :restaurant_reviews,  through: :booking_restaurants

  validates :name, presence: true
  validates :address, presence: true
  validates :price, presence: true
  validates :category, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def average_rating
    return 5 if restaurant_reviews.empty?
    sum = 0
    restaurant_reviews.each do |restaurant_review|
      sum += restaurant_review.rating
    end
    @average_rating = sum / restaurant_reviews.count
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]
  skip_after_action :verify_policy_scoped, only: :index
  
  def index
    @trip = Trip.find(params[:trip_id])
    @restaurants = Restaurant.near(@trip.location, 20)

    if params[:search]&.fetch(:price_max).present?
      @price_max = params[:search][:price_max]
      @restaurants = @restaurants.where("price <= ?", @price_max)
    end

    if params[:search]&.fetch(:category).present?
      @category = params[:search][:category]
      @restaurants = @restaurants.where("category = ?", @category)
    end

    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant }),
        info_price: "#{restaurant.price.round}€"				
      }
    end
  end

  def show
    @booking_restaurant = BookingRestaurant.new
    @trip = Trip.find(params[:trip_id])
    @restaurant = Restaurant.find(params[:id])
    @markers = [{ lat: @restaurant.latitude, lng: @restaurant.longitude, infoWindow: render_to_string(partial: "info_window", locals: { restaurant: @restaurant }),
    info_price: @restaurant.price }]
    @people = @trip.number_of_travellers
    @markers = [{ lat: @restaurant.latitude, lng: @restaurant.longitude }]
    @duration = @trip.end_date - @trip.start_date
		@price = @restaurant.price * @people
    authorize(@restaurant)
    @restaurantreservation = BookingRestaurant.find_by(restaurant: @restaurant, trip: @trip)
    @restaurant_review = RestaurantReview.new
    @restaurant_reviews = @restaurant.restaurant_reviews
    @average_rating = @restaurant_reviews.average(:rating)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    authorize_restaurant
  end

  def authorize_restaurant
		authorize(@restaurant)
	end

end

app/views/restaurants/_info_window.html.erb
<div class="card-window">
  <div class="photo-info">
    <% if restaurant.photos.any? %>
      <%= cl_image_tag restaurant.photos.first.key %>
    <% end %>
  </div>
  <h2><%= restaurant.name %></h2>
  <p><%= restaurant.address %></p>
</div>

app/views/restaurants/index.html.erb
<div class="container-fluid py-1">
<%= render 'shared/tab' %>
  <div class='margin_filtres'>
  <%= simple_form_for :search, url: trip_restaurants_path, method: 'GET', html: { class: 'form-inline' } do |f| %>
    <%= f.input :price_max, class: "border-right", placeholder: 'prix maximum', label: false, input_html: { value: @price_max } %>
    <%= f.input :category, label: false, collection: Restaurant::CATEGORIES, prompt: 'catégorie', selected: @category, include_blank: 'Toutes' %> 
    <%= f.submit "Rechercher", class: "btn btn-primary hover_btn_search no_border background_color_grey border_light_grey border-right padding-12-px text_color_green" %>
  <% end %>
  </div>


  <div class="content">
    <div class="cards">
      <% @restaurants.each do |restaurant| %>
       <%= link_to trip_restaurant_path(trip_id: @trip.id, id: restaurant.id) do %>
          <div class="card-trip">  
            <%= cl_image_tag restaurant.photos.first.key %>
            <div class="card-trip-infos">
              <div class='card-trip-text'>
                <p><%= restaurant.address %></p>
                <h2 class="pb-2 mb-2"><%= restaurant.name %></h2>
              </div>
              <div>
                <h2 class="card-trip-pricing"><%= restaurant.price %>€</h2>
              </div>
            </div>
          </div> 
       <% end %> 
      <% end %>
    </div>
    <div id="trip-box" style="width: 300px; height: 100vh;">
      <ul class="list-inline nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="t-tab-underlined nav-link active" id="trip-tab" data-toggle="tab" href="#trip" role="tab" aria-controls="trip" aria-selected="false">Mon voyage</a> 
        </li>
        <li class="nav-item">
          <a class="t-tab-underlined nav-link" id="map-tab" data-toggle="tab" href="#map" role="tab" aria-controls="map" aria-selected="true">Carte</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="trip" role="tabpanel" aria-labelledby="trip-tab">
          <div class="trip-column">
            <div class="trip-card-title">
              <h6>Restaurants</h6>
            </div>
            <% unless @trip.restaurants.empty? %>
              <% @trip.restaurants.each do |restaurant| %>
                <div id="trip-card">
                  <div class="left">
                    <p><%= restaurant.name %></p>
                    <p><span><%= restaurant.price %>€/ personne</span></p>
                    <p><%= @trip.start_date %></p>
                  </div>
                  <div class="right">
                    <a data-dismiss="alert" aria-label="Close">
                      <i class="fas fa-times"></i>
                    </a>
                  </div>
                </div>
              <% end %>
            <% end %>
            <div>
              <div class="trip-card-title">
                <h6>Hébergements</h6>
              </div>
              <% unless @trip.flats.empty? %>
                <% @trip.flats.each do |flat| %>
                  <div id="trip-card">
                    <div class="left">
                      <p><%= flat.name %></p>
                      <p><span><%= flat.price %>€/ nuité par personne</span></p>
                      <p><%= @trip.start_date %> - <%= @trip.end_date %></p>
                    </div>
                    <div class="right">
                      <a data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-times"></i>
                      </a>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div>
              <div class="trip-card-title">
                <h6>Activités</h6>
              </div>
              <% unless @trip.activities.empty? %>
                <% @trip.activities.each do |activity| %>
                  <div id="trip-card">
                    <div class="left">
                      <p><%= activity.name %></p>
                      <p><span><%= activity.price %>€/ personne</span></p>
                      <p><%= @trip.start_date %></p>
                    </div>
                    <div class="right">
                      <a data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-times"></i>
                      </a>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="book-box">
              <%= link_to "Réserver", trip_path(@trip), class: "important-btn" %>
            </div>
          </div> <!--end-->
        </div>
        <div class="tab-pane fade"
          id="map"
          role="tabpanel"
          aria-labelledby="map-tab"
          style="width: 300px; height: 100vh;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container-fluid py-4">
  <div class="content">
    <div style='width: 100%'>
      <div>
        <div class='show-title'>
          <%= link_to ('<i class="far return-fa fa-angle-left"></i>').html_safe, trip_flats_path(@trip) %>
          <div>
            <h4><%= @restaurant.address %></h4>
            <h1><%= @restaurant.name %></h1>
          </div>
        </div>
        <div class="rounded px-3">
          <div class="gallery">
            <div class="img-principale">
              <%= cl_image_tag @restaurant.photos.first.key, height: 385, crop: :fill, class:"w-100 h-100" %>
            </div>
            <div class="img-secondaires">
              <% (1..3).each do |number| %>
                <% if @restaurant.photos[number].nil? %>
                  <button class="img-secondaire btn" type="button" data-toggle="modal" data-target="#exampleModalCenter" style="background-image: url(<%= cl_image_path 'photo.jpg' %>);"></button>
                <% else %>
                  <!-- Button trigger modal -->
                  <button class="img-secondaire btn" type="button" data-toggle="modal" data-target="#exampleModalCenter-<%= number %>" style="background-image: url(<%= cl_image_path @restaurant.photos[number].key %>);"></button>

                  <!-- Modal -->
                  <div class="modal fade" id="exampleModalCenter-<%= number %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content restaurant-modal">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <!-- Code carroussel -->
                          <%= cl_image_tag @restaurant.photos[number].key %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- restaurant card -->
      <div class="row p-4">
        <div class="col-md-8">
      <%# <div class="element"> %>
          <div>
            <p><%= @restaurant.description %></p>
            <div>
              <p>Ce restaurant est noté :
              <% @restaurant.average_rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
              <% (5 - @restaurant.average_rating).times do %>
                <i class="far fa-star"></i>
              <% end %>
              </p>
              <div class="reviews">
                <h2>Détail des évaluations</h2>
                <% @restaurant_reviews.each do |restaurant_review| %>
                  <p><% restaurant_review.rating.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% (5 - restaurant_review.rating).times do %>
                    <i class="far fa-star"></i>
                  <% end %>
                  <p><%= restaurant_review.content %></p>
                <% end %>
              </div>
              <% if @restaurantreservation %>
                <div class="review">
                  <h4>Laissez une évaluation</h4>
                  <%= simple_form_for @restaurant_review, url: restaurants_booking_restaurant_reviews_path(@restaurantreservation, html: { class: "review_form" }) do |f| %>
                    <%= f.input :content %>
                    <%= f.input :rating, collection: (1..5).to_a, label: "notez votre expérience" %>
                    <%= f.submit class: "d-none" %>
                  <% end %>
                </div>
              <% end %>
            </div>
            <%#= link_to "Retour aux hébergements", restaurants_path, class:"btn btn-secondary" %>
          </div>
        </div>

        <div class="col-md-4">
          <div>
            <!-- Booking card -->
            <div id="form_booking">
              <div class="d-flex justify-content-between mt-2">
                <div class="important">

                  <p><%= @restaurant.price %>€ / personne<span style="font-size: 16px"></span></p>

                </div>
              </div>
              <p>Cuisine: <%= @restaurant.category %></p>
              <div>
                <%= simple_form_for [@restaurant, @booking_restaurant], url:  restaurant_restaurants_bookings_path(@restaurant) do |f| %>
                  <%= f.input :trip_id, as: :hidden, input_html:{value:@trip.id} %>
                  <%= f.input :start_date, placeholder: "Date", as: :string, required: false, input_html: { class: "datepicker", value: @trip.start_date}, order: [:day, :month, :year], label: false %>
                  <%= f.button :submit, "Réserver", class: "btn btn-primary w-100" %>
                <% end %>
              </div>
              <div class="important">
                <div class="d-flex justify-content-between mt-3">
                  <p><strong>Total</strong></p>
                  <p><strong><%= @price %>€</strong></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="pb-2"><h4>Emplacement</h4>
        <div id="map"
          style="width: 100%; height: 600px; border-radius: 10px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
    <div id="trip-box" style="width: 300px; height: 100vh;">
      <ul class="list-inline nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="t-tab-underlined nav-link active" id="trip-tab" data-toggle="tab" href="#trip" role="tab" aria-controls="trip" aria-selected="false">Mon voyage</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="trip" role="tabpanel" aria-labelledby="trip-tab">
          <div class="trip-column">
            <div class="trip-card-title">
              <h6>Restaurants</h6>
            </div>
            <% unless @trip.restaurants.empty? %>
              <% @trip.restaurants.each do |restaurant| %>
                <div id="trip-card">
                  <div class="left">
                    <p><%= restaurant.name %></p>
                    <p><span><%= restaurant.price %>€ / par personne</span></p>
                    <p><%= @trip.start_date %></p>
                  </div>
                  <div class="right">
                    <a data-dismiss="alert" aria-label="Close">
                      <i class="fas fa-times"></i>
                    </a>
                  </div>
                </div>
              <% end %>
            <% end %>
            <div>
              <div class="trip-card-title">
                <h6>Hébergements</h6>
              </div>
              <% unless @trip.flats.empty? %>
                <% @trip.flats.each do |flat| %>
                  <div id="trip-card">
                    <div class="left">
                      <p><%= flat.name %></p>
                      <p><span><%= flat.price %>€ / nuité par personne</span></p>
                      <p><%= @trip.start_date %> - <%= @trip.end_date %></p>
                    </div>
                    <div class="right">
                      <a data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-times"></i>
                      </a>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div>
              <div class="trip-card-title">
                <h6>Activités</h6>
              </div>
              <% unless @trip.activities.empty? %>
                <% @trip.activities.each do |activity| %>
                  <div id="trip-card">
                    <div class="left">
                      <p><%= activity.name %></p>
                      <p><span><%= activity.price %>€ / personne</span></p>
                      <p><%= @trip.start_date %></p>
                    </div>
                    <div class="right">
                      <a data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-times"></i>
                      </a>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>